"""Create a baseline migrations

Revision ID: e2d4278ae64b
Revises: 
Create Date: 2024-03-27 22:46:33.110960

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'e2d4278ae64b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
